variable asg_name {}
variable vpc_zone_identifier {}
variable availability_zones {}
variable load_balancers {}
variable launch_configuration_name {}
variable min_size {}
variable max_size {}
variable instance_name {}
variable env {}
